# Generated by Django 5.1.2 on 2024-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_deposit_status_alter_deposit_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
