# Generated by Django 5.1.2 on 2024-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_remove_deposit_transaction_id_alter_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
