# Generated by Django 5.1.2 on 2024-11-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_deposit_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_id',
        ),
    ]
